version: "3"

services:
  redis:
    image: redis
    container_name: music_redis
    volumes:
      - redis_data:/data
    command: --appendonly yes --requirepass "123456"
    restart: always

  web:
    build: .
    container_name: music_web
    env_file: .env
    volumes:
      - media:/usr/src/app/media/
      - static:/usr/src/app/static/
    depends_on:
      - redis
      - rabbit
    restart: always

  rabbit:
    container_name: music_rabbit
    image: rabbitmq:3.8.0-management-alpine
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  frpc-inter:
    image: snowdreamtech/frpc
    container_name: music_frpc_inter
    volumes:
      - "./frpc/frpc1.ini:/etc/frp/frpc.ini"
    restart: always

  frpc-out:
    image: snowdreamtech/frpc
    container_name: music_frpc_out
    volumes:
      - "./frpc/frpc2.ini:/etc/frp/frpc.ini"
    restart: always

volumes:
  redis_data:
  media:
  static:
  rabbit_data:
