version: "3"

services:
  redis:
    image: redis
    container_name: music_redis
    volumes:
      - redis_data:/data
    command: --appendonly yes --requirepass "123456"
    restart: always
    ports:
      - "6377:6379"

  web:
    build: .
    container_name: music_web
    env_file: .env
    volumes:
      - media:/usr/src/app/media/
      - static:/usr/src/app/static/
    restart: always

  nginx:
    build: ./nginx
    container_name: music_nginx
    ports:
      - "8000:8000"
    volumes:
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media
    restart: always

  rabbit:
    container_name: music_rabbit
    image: rabbitmq:3.8.0-management-alpine
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin

  frpc:
    image: snowdreamtech/frpc
    container_name: music_frpc
    volumes:
      - "./frpc/frpc.ini:/etc/frp/frpc.ini"
    restart: always

volumes:
  redis_data:
  media:
  static:
