version: "3"

services:
  redis:
    image: redis
    container_name: gamenews_redis
    volumes:
      - redis_data:/data
    command: --appendonly yes --requirepass "123456"
    restart: always
    ports:
      - "6377:6379"
  web:
    build: .
    container_name: music_web
    env_file: .env
    volumes:
      - .:/usr/src/app/
    restart: always

  nginx:
    build: ./nginx
    container_name: music_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    restart: always

volumes:
  redis_data: